import { defineObject } from './defineObject'
import type { WorldObjectDefinition } from '../worldObjectTypes'

/** Remaining registered types not yet split into named production modules. */
export const REMAINING_OBJECT_DEFINITIONS: readonly WorldObjectDefinition[] = Object.freeze([
  defineObject({
    id: 'ossuary.floor.slab',
    family: 'architecture',
    materialKey: 'floorSlab',
    castShadow: false,
    receiveShadow: true,
    renderMode: 'instanced',
    visualBounds: [1.04, 0.035, 1],
    anchorPolicy: 'floor',
  }),
  defineObject({
    id: 'ossuary.floor.ash-slab',
    family: 'architecture',
    materialKey: 'ashStone',
    castShadow: false,
    receiveShadow: true,
    renderMode: 'instanced',
    visualBounds: [1.04, 0.035, 1],
    anchorPolicy: 'floor',
  }),
  defineObject({
    id: 'ossuary.floor.seal-slab',
    family: 'architecture',
    materialKey: 'sealStone',
    castShadow: false,
    receiveShadow: true,
    renderMode: 'instanced',
    visualBounds: [1.04, 0.035, 1],
    anchorPolicy: 'floor',
  }),
  defineObject({
    id: 'ossuary.floor.inlay',
    family: 'metal',
    materialKey: 'verdigris',
    castShadow: false,
    receiveShadow: true,
    renderMode: 'instanced',
    anchorPolicy: 'floor',
  }),
  defineObject({
    id: 'ossuary.floor.broken-edge',
    family: 'architecture',
    materialKey: 'ashStone',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'instanced',
    anchorPolicy: 'floor',
  }),
  defineObject({
    id: 'ossuary.floor.pit-rim',
    family: 'architecture',
    materialKey: 'floorSlab',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'instanced',
    anchorPolicy: 'floor',
  }),
  defineObject({
    id: 'ossuary.wall.break',
    family: 'architecture',
    materialKey: 'darkStone',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'instanced',
    visualBounds: [0.68, 0.68, 0.68],
    anchorPolicy: 'structural',
  }),
  defineObject({
    id: 'ossuary.arch.rib',
    family: 'architecture',
    materialKey: 'darkStone',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'instanced',
    visualBounds: [0.24, 1.7, 0.22],
    anchorPolicy: 'structural',
  }),
  defineObject({
    id: 'ossuary.arch.lancet',
    family: 'architecture',
    materialKey: 'darkStone',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'instanced',
    visualBounds: [1.5, 2.25, 0.22],
    anchorPolicy: 'structural',
  }),
  defineObject({
    id: 'ossuary.arch.lancet-broken',
    family: 'architecture',
    materialKey: 'recessStone',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'instanced',
    visualBounds: [1.35, 1.8, 0.26],
    anchorPolicy: 'structural',
  }),
  defineObject({
    id: 'ossuary.buttress.split',
    family: 'architecture',
    materialKey: 'darkStone',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'instanced',
    visualBounds: [0.56, 1.9, 0.5],
    collision: { kind: 'box', colliderKind: 'blocker', navigationBlocking: true },
    anchorPolicy: 'structural',
  }),
  defineObject({
    id: 'ossuary.niche.cluster',
    family: 'burial',
    materialKey: 'recessStone',
    castShadow: false,
    receiveShadow: true,
    renderMode: 'instanced',
    visualBounds: [0.1, 1.25, 1.15],
    anchorPolicy: 'wall',
  }),
  defineObject({
    id: 'ossuary.reliquary.chain',
    family: 'metal',
    materialKey: 'iron',
    castShadow: true,
    receiveShadow: false,
    renderMode: 'instanced',
    visualBounds: [0.24, 1.7, 0.12],
    anchorPolicy: 'hanging',
  }),
  defineObject({
    id: 'ossuary.wall.ledge',
    family: 'architecture',
    materialKey: 'floorSlab',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'instanced',
    visualBounds: [0.18, 0.16, 1.1],
    anchorPolicy: 'wall',
  }),
  defineObject({
    id: 'ossuary.grave.plaque',
    family: 'burial',
    materialKey: 'bone',
    castShadow: false,
    receiveShadow: true,
    renderMode: 'instanced',
    visualBounds: [0.05, 0.4, 0.28],
    anchorPolicy: 'wall',
  }),
  defineObject({
    id: 'ossuary.metal.bronze-brace',
    family: 'metal',
    materialKey: 'bronze',
    castShadow: false,
    receiveShadow: true,
    renderMode: 'instanced',
    visualBounds: [0.08, 0.64, 0.08],
  }),
  defineObject({
    id: 'ossuary.niche.recess',
    family: 'burial',
    materialKey: 'recessStone',
    castShadow: false,
    receiveShadow: true,
    renderMode: 'instanced',
    visualBounds: [0.06, 0.74, 0.62],
    anchorPolicy: 'wall',
  }),
  defineObject({
    id: 'ossuary.niche.arch',
    family: 'metal',
    materialKey: 'bronze',
    castShadow: false,
    receiveShadow: false,
    renderMode: 'instanced',
    visualBounds: [0.58, 0.58, 0.07],
    anchorPolicy: 'wall',
  }),
  defineObject({
    id: 'ossuary.sarcophagus.lid',
    family: 'burial',
    materialKey: 'bone',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'instanced',
    anchorPolicy: 'floor',
  }),
  defineObject({
    id: 'ossuary.marker.body',
    family: 'burial',
    materialKey: 'darkStone',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'instanced',
    anchorPolicy: 'floor',
  }),
  defineObject({
    id: 'ossuary.marker.cap',
    family: 'burial',
    materialKey: 'bone',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'instanced',
    anchorPolicy: 'floor',
  }),
  defineObject({
    id: 'ossuary.rubble.cluster',
    family: 'dressing',
    materialKey: 'darkStone',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'instanced',
    visualBounds: [0.68, 0.68, 0.68],
    collision: { kind: 'box', colliderKind: 'blocker', navigationBlocking: true },
    anchorPolicy: 'floor',
  }),
  defineObject({
    id: 'ossuary.candle.body',
    family: 'dressing',
    materialKey: 'bone',
    castShadow: false,
    receiveShadow: false,
    renderMode: 'instanced',
  }),
  defineObject({
    id: 'ossuary.candle.flame',
    family: 'dressing',
    materialKey: 'ember',
    castShadow: false,
    receiveShadow: false,
    renderMode: 'instanced',
  }),
  defineObject({
    id: 'ossuary.banner',
    family: 'dressing',
    materialKey: 'cloth',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'instanced',
    anchorPolicy: 'wall',
  }),
  defineObject({
    id: 'ossuary.root.cluster',
    family: 'dressing',
    materialKey: 'iron',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'instanced',
  }),
  defineObject({
    id: 'ossuary.silhouette.mass',
    family: 'architecture',
    materialKey: 'ashStone',
    castShadow: false,
    receiveShadow: false,
    renderMode: 'instanced',
    visualBounds: [2.4, 3.2, 0.55],
    anchorPolicy: 'structural',
  }),
  defineObject({
    id: 'ossuary.silhouette.column',
    family: 'architecture',
    materialKey: 'ashStone',
    castShadow: false,
    receiveShadow: false,
    renderMode: 'instanced',
    visualBounds: [0.55, 3.4, 0.55],
    anchorPolicy: 'structural',
  }),
  defineObject({
    id: 'ossuary.light.candelabrum',
    family: 'lighting',
    materialKey: 'bronze',
    castShadow: true,
    receiveShadow: false,
    renderMode: 'unique',
    lighting: { kind: 'actual' },
    anchorPolicy: 'floor',
  }),
  defineObject({
    id: 'ossuary.light.reliquary-lantern',
    family: 'lighting',
    materialKey: 'bronze',
    castShadow: true,
    receiveShadow: false,
    renderMode: 'unique',
    lighting: { kind: 'emissive' },
    anchorPolicy: 'wall',
  }),
  defineObject({
    id: 'ossuary.light.double-sconce',
    family: 'lighting',
    materialKey: 'bronze',
    castShadow: true,
    receiveShadow: false,
    renderMode: 'unique',
    lighting: { kind: 'emissive' },
    anchorPolicy: 'wall',
  }),
  defineObject({
    id: 'ossuary.light.ember-bowl',
    family: 'lighting',
    materialKey: 'bronze',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'unique',
    lighting: { kind: 'actual' },
    anchorPolicy: 'floor',
  }),
  defineObject({
    id: 'ossuary.light.spectral-reliquary',
    family: 'lighting',
    materialKey: 'verdigris',
    castShadow: true,
    receiveShadow: false,
    renderMode: 'unique',
    lighting: { kind: 'actual' },
    anchorPolicy: 'floor',
  }),
  defineObject({
    id: 'ossuary.metal.burial-screen',
    family: 'metal',
    materialKey: 'iron',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'instanced',
    visualBounds: [1.4, 1.3, 0.09],
  }),
  defineObject({
    id: 'ossuary.reliquary.broken',
    family: 'burial',
    materialKey: 'bone',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'instanced',
  }),
  defineObject({
    id: 'ossuary.landmark.arena-seal',
    family: 'landmark',
    materialKey: 'bronze',
    castShadow: false,
    receiveShadow: true,
    renderMode: 'unique',
    anchorPolicy: 'floor',
  }),
  defineObject({
    id: 'ossuary.landmark.veil-monolith',
    family: 'landmark',
    materialKey: 'darkStone',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'unique',
    visualBounds: [0.45, 2.2, 0.45],
    collision: { kind: 'box', colliderKind: 'blocker', navigationBlocking: true },
    anchorPolicy: 'floor',
  }),
  defineObject({
    id: 'ossuary.landmark.reliquary-plinth',
    family: 'landmark',
    materialKey: 'darkStone',
    castShadow: true,
    receiveShadow: true,
    renderMode: 'unique',
    anchorPolicy: 'floor',
  }),
  defineObject({
    id: 'ossuary.corridor.bell',
    family: 'metal',
    materialKey: 'bronze',
    castShadow: true,
    receiveShadow: false,
    renderMode: 'unique',
    anchorPolicy: 'hanging',
  }),
])
