#!/usr/bin/env python3
"""Generate state/REPOMAP.md: compact tree, key symbols, and local dependency hints.

Stdlib only. Hidden infrastructure directories that materially define agent behavior
(.agents/.claude/.cursor/.github/.leanloop) are included; caches and VCS metadata are not.
"""
from __future__ import annotations

import argparse
import os
import re
from pathlib import Path

from leanloop_common import find_repo_root

IGNORE_DIRS = {
    ".git", "node_modules", "dist", "build", ".next", "__pycache__", ".venv",
    "venv", "target", "coverage", ".turbo", ".cache", "vendor", ".idea",
    ".vscode", "out", ".leanloop-worktrees",
}
INCLUDE_HIDDEN_DIRS = {".agents", ".claude", ".cursor", ".github", ".leanloop"}
IGNORE_FILES = {
    "package-lock.json", "pnpm-lock.yaml", "yarn.lock", "poetry.lock", "Cargo.lock",
    "uv.lock", "composer.lock", ".DS_Store",
}
SYMBOL_RE = {
    ".py": re.compile(r"^(?:async\s+)?(?:class|def)\s+(\w+)", re.M),
    ".ts": re.compile(r"^export\s+(?:default\s+)?(?:async\s+)?(?:function|class|const|interface|type|enum)\s+(\w+)", re.M),
    ".tsx": re.compile(r"^export\s+(?:default\s+)?(?:async\s+)?(?:function|class|const|interface|type)\s+(\w+)", re.M),
    ".js": re.compile(r"^(?:export\s+)?(?:async\s+)?(?:function|class|const)\s+(\w+)", re.M),
    ".jsx": re.compile(r"^(?:export\s+)?(?:async\s+)?(?:function|class|const)\s+(\w+)", re.M),
    ".go": re.compile(r"^func\s+(?:\([^)]*\)\s+)?(\w+)", re.M),
    ".rs": re.compile(r"^(?:pub(?:\([^)]*\))?\s+)?(?:fn|struct|enum|trait)\s+(\w+)", re.M),
    ".rb": re.compile(r"^\s*(?:class|module|def)\s+([\w.]+)", re.M),
    ".java": re.compile(r"^\s*(?:public|protected)?\s*(?:static\s+)?(?:final\s+)?(?:class|interface|enum|record)\s+(\w+)", re.M),
}
IMPORT_RE = {
    ".py": re.compile(r"^(?:from\s+([\w.]+)\s+import|import\s+([\w.]+))", re.M),
    ".ts": re.compile(r"(?:from\s+|import\s*\()\s*['\"]([^'\"]+)['\"]", re.M),
    ".tsx": re.compile(r"(?:from\s+|import\s*\()\s*['\"]([^'\"]+)['\"]", re.M),
    ".js": re.compile(r"(?:from\s+|require\s*\(|import\s*\()\s*['\"]([^'\"]+)['\"]", re.M),
    ".jsx": re.compile(r"(?:from\s+|require\s*\(|import\s*\()\s*['\"]([^'\"]+)['\"]", re.M),
}


def read_prefix(path: Path, limit: int = 250_000) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")[:limit]
    except OSError:
        return ""


def line_count(path: Path) -> int:
    try:
        with path.open("rb") as f:
            return sum(1 for _ in f)
    except OSError:
        return 0


def symbols(path: Path, max_symbols: int) -> list[str]:
    rx = SYMBOL_RE.get(path.suffix.lower())
    if not rx:
        return []
    return rx.findall(read_prefix(path))[:max_symbols]


def local_imports(path: Path, max_imports: int) -> list[str]:
    rx = IMPORT_RE.get(path.suffix.lower())
    if not rx:
        return []
    raw = rx.findall(read_prefix(path))
    values: list[str] = []
    for match in raw:
        if isinstance(match, tuple):
            value = next((x for x in match if x), "")
        else:
            value = match
        if not value:
            continue
        # Only retain likely local/relative imports; external package lists are noisy.
        if value.startswith((".", "src", "app", "packages", "lib", "internal")):
            if value not in values:
                values.append(value)
        if len(values) >= max_imports:
            break
    return values


def hidden_dir_allowed(name: str) -> bool:
    return not name.startswith(".") or name in INCLUDE_HIDDEN_DIRS


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate a compact LeanLoop repository map")
    ap.add_argument("repo_root", nargs="?", default=".")
    ap.add_argument("--max-depth", type=int, default=4)
    ap.add_argument("--max-chars", type=int, default=9000)
    ap.add_argument("--max-files", type=int, default=12, help="files shown per directory")
    args = ap.parse_args()

    root = Path(args.repo_root).resolve()
    if not root.exists():
        raise SystemExit(f"repo not found: {root}")
    # If called from a nested support directory, still map the user repo when '.' is used.
    if args.repo_root == ".":
        root = find_repo_root(root)

    lines = [
        "# REPOMAP",
        "<!-- generated by scripts/leanloop/repomap.py; do not hand-edit -->",
        "",
        "Compact navigation map. Confirm exact behavior with targeted grep/ranged reads.",
        "",
        "## Tree & entry points",
    ]
    dependency_hints: list[str] = []

    for dirpath_s, dirnames, filenames in os.walk(root):
        dirpath = Path(dirpath_s)
        rel_path = dirpath.relative_to(root)
        rel = "." if rel_path == Path(".") else rel_path.as_posix()
        depth = 0 if rel == "." else len(rel_path.parts)

        dirnames[:] = sorted(
            d for d in dirnames
            if d not in IGNORE_DIRS and hidden_dir_allowed(d)
        )
        if depth >= args.max_depth:
            dirnames[:] = []

        files = sorted(
            f for f in filenames
            if f not in IGNORE_FILES and (not f.startswith(".") or f in {".gitignore", ".editorconfig"})
        )
        if rel != ".":
            lines.append(f"{'  ' * (depth - 1)}- **{rel}/** ({len(files)} files)")

        for idx, name in enumerate(files[: args.max_files]):
            path = dirpath / name
            syms = symbols(path, 5)
            imps = local_imports(path, 3)
            note_parts = []
            if syms:
                note_parts.append("symbols: " + ", ".join(syms))
            if imps:
                note_parts.append("imports: " + ", ".join(imps))
                dependency_hints.append(f"- `{path.relative_to(root).as_posix()}` -> {', '.join(f'`{i}`' for i in imps)}")
            note = " -- " + "; ".join(note_parts) if note_parts else ""
            lines.append(f"{'  ' * depth}- {name} ({line_count(path)}L){note}")
        if len(files) > args.max_files:
            lines.append(f"{'  ' * depth}- ... +{len(files) - args.max_files} more")

    if dependency_hints:
        lines.extend(["", "## Local dependency hints", *dependency_hints[:40]])

    out = "\n".join(lines)
    if len(out) > args.max_chars:
        out = out[: args.max_chars].rstrip() + "\n\n... (truncated; deepen with targeted grep/read rather than raising the global map budget)"

    state = root / "state"
    state.mkdir(parents=True, exist_ok=True)
    dest = state / "REPOMAP.md"
    dest.write_text(out + "\n", encoding="utf-8")
    print(f"wrote {dest} ({len(out)} chars ~ {len(out)//4} rough tokens)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
